plugins/gui/visualizer_gui/blueprints/base.py
# -*- encoding: utf-8 -*-
from flask import Blueprint, jsonify, render_template, redirect, request, url_for, send_from_directory
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)
from app.app import db, login_manager
from .forms import LoginForm, CreateAccountForm
from app.util import verify_pass
import logging
_logger = logging.getLogger(__name__)

def new_bp(plugin_folder, core_ep, store_ep, db, Base):
    
    bp = Blueprint("base_bp", __name__, url_prefix='', template_folder=plugin_folder+"/templates", static_folder=plugin_folder+"/static")
    User = core_ep.User

    ### static assets for AdminLTE
    # TODO: To use some minLTE package instead of linkink content in gui
    @bp.route('/static/assets/<path:path>')
    def adminlte_assets(path):
        #_logger.info("static AdminLTE assets folder: "+plugin_folder+"/static/adminlte_assets/"+path)
        return send_from_directory(plugin_folder+"/static/adminlte_assets",  path)

    ### static favicon
    # @bp.route('/<path:path>/favicon.ico')
    # @bp.route('/favicon.ico')
    # def favicon(path):
        #_logger.info("static favicon folder: "+plugin_folder+"/static/favicon/"+path)
    #    return send_from_directory(plugin_folder+"/static/favicon.ico",  path)

    ### static javascript files for gui plugin blueprints
    @bp.route('/static/js/<path:path>')
    def js_assets(path):
        #_logger.info("static gui js folder: "+plugin_folder+"/static/js/"+path)
        return send_from_directory(plugin_folder+"/static/js",  path)

    ##Login & Registration
    @bp.route('/login', methods=['GET', 'POST'])
    def login():
        login_form = LoginForm(request.form)
        if 'login' in request.form:
            # read form data
            username = request.form['username']
            password = request.form['password']
            # Locate user
            user = User.query.filter_by(username=username).first()
            # Check the password
            if user and verify_pass( password, user.password):

                login_user(user)
                return redirect('/')

            # Something (user or pass) is not ok
            return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

        if not current_user.is_authenticated:
            return render_template( 'accounts/login.html',
                                    form=login_form)
        #return redirect(url_for('data_logger.index'))
        return redirect(url_for('home_bp.index'))

    @bp.route('/register', methods=['GET', 'POST'])
    def register():
        login_form = LoginForm(request.form)
        create_account_form = CreateAccountForm(request.form)
        if 'register' in request.form:

            username  = request.form['username']
            email     = request.form['email'   ]

            # Check usename exists
            user = User.query.filter_by(username=username).first()
            if user:
                return render_template( 'accounts/register.html', 
                                        msg='Username already registered',
                                        success=False,
                                        form=create_account_form)

            # Check email exists
            user = User.query.filter_by(email=email).first()
            if user:
                return render_template( 'accounts/register.html', 
                                        msg='Email already registered', 
                                        success=False,
                                        form=create_account_form)

            # else we can create the user
            user = User(**request.form)
            db.session.add(user)
            db.session.commit()

            return render_template( 'accounts/register.html', 
                                    msg='User created please <a href="/login">login</a>', 
                                    success=True,
                                    form=create_account_form)

        else:
            return render_template( 'accounts/register.html', form=create_account_form)

    @bp.route('/logout')
    def logout():
        logout_user()
        return redirect(url_for('base_bp.login'))

    @bp.route('/shutdown')
    def shutdown():
        func = request.environ.get('werkzeug.server.shutdown')
        if func is None:
            raise RuntimeError('Not running with the Werkzeug Server')
        func()
        return 'Server shutting down...'

    ## Errors

    @login_manager.unauthorized_handler
    def unauthorized_handler():
        return render_template("error_pages/page-403.html"), 403

    @bp.errorhandler(403)
    def access_forbidden(error):
        return render_template('error_pages/page-403.html'), 403

    @bp.errorhandler(404)
    def not_found_error(error):
        print("Error : " , str(error))
        return render_template("error_pages/page-404.html"), 404

    @bp.errorhandler(500)
    def internal_error(error):
        return render_template('error_pages/page-500.html'), 500

    return bp

plugins/gui/visualizer_gui/templates/includes/footer.html
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <a target="_blank" rel="noopener noreferrer" href="https://github.com/harveybc/data-logger">data_logger</a>
    - by <a target="_blank" rel="noopener noreferrer" href="https://profile.codersrank.io/user/harveybc">harveybc</a>
    <div class="float-right d-none d-sm-inline-block">
      <a target="_blank" rel="noopener noreferrer" 
          href="https://github.com/harveybc"><i class="fab fa-github"></i>Github</a> 
    </div>
  </footer>

plugins/gui/visualizer_gui/templates/includes/navigation.html
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link"><i class="fas fa-home"></i>Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="https://github.com/harveybc/data-logger" class="nav-link"><i class="fab fa-github"></i>GitHub</a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

plugins/gui/visualizer_gui/templates/includes/sidebar.html
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="/static/assets/img/data_loggerLogo.png" alt="data_logger Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">data_logger</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/static/assets/img/debianlogo.png" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info"> 
          <a href="{{ url_for('base_bp.logout') }}" class="d-block">
            {{ current_user.username }} - Logout
          </a>
        </div>
      </div>
      
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="/" class="nav-link" id="menu-dashboard">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          
          {% for process in p_config_store.store_plugin_config.processes %}
            <li class="nav-item has-treeview"  id="menu-{{ process.name }}">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-book"></i>
                <p>
                  {{ process.name }}
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
              {% for table in process.tables %}
                  <li class="nav-item">
                    <a href="/{{ process.name }}/{{ table.name }}/view_index " class="nav-link" id="submenu-{{ table.name }}"+>
                      <i class="far fa-clock nav-icon"></i>
                      <p>{{ table.name }}</p>
                    </a>
                  </li>
              {% endfor %}
              </ul>
            </li>
          {% endfor %}
                             

          
          <li class="nav-item has-treeview" id="menu-admin">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-user-tie"></i>
              <p>
                Admin
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/dashboard/users" class="nav-link" id="menu-authentication">
                  <i class="nav-icon fas fa-users"></i>
                  <p>Users</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/dashboard/authorization" class="nav-link"  id="menu-authorization">
                  <i class="nav-icon fas fa-key"></i>
                  <p>Authorization</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/dashboard/logs" class="nav-link"  id="menu-log">
                  <i class="nav-icon fas fa-book"></i>
                  <p>Logs</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/dashboard/processes" class="nav-link" id="menu-processes">
                  <i class="nav-icon fas fa-network-wired"></i>
                  <p>
                    Instances
                  </p>
                </a>
              </li>
            </ul>
          </li>
          </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  